title: "jekyll-timeline - Source and Examples"
description: This is a small group of html and css includes for Jekyll that lets you create a beautiful timeline.
baseurl: "/jekyll-timeline" # the subpath of your site, e.g. /blog
# url: "http://www.simple.gy/jekyll-timeline/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: simplgy
github_username:  simplgy
permalink: /:title/
host: 0.0.0.0 # allows external access
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - '/README.md'
  - '*.sass'
# github:
#   repositoryName: '/'